version: build{build}

environment:
    matrix:
        - PYTHON: "C:\\Python36"

install:
    - "%PYTHON%\\python.exe -m pip install pipenv"
    - "%PYTHON%\\Scripts\\pipenv.exe install"

test_script:
    - "%PYTHON%\\Scripts\\pipenv.exe run python wallpaper\\test.py"

build: false
cache:
    - '%LOCALAPPDATA%\pip\cache'
    - '%USERPROFILE%\.cache\pre-commit'
